name: CI/CD Pipeline

on:
  push:
    branches:
      - Prueba-3

env:
  DOCKER_COMPOSE_VERSION: 1.27.4
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: leonel1805/my-nginx-image:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Update Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get -y install curl
        sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose up -d
